version: "3.9"

services:
  fl-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - fraud-net
    volumes:
      - ./mlruns:/app/mlruns
      - ./checkpoints:/app/checkpoints
    environment:
      NUM_ROUNDS: "10"
      MIN_CLIENTS: "3"
      MLFLOW_TRACKING_URI: "http://mlflow:5000"

  fl-client-0:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      - fraud-net
    volumes:
      - ./data/processed:/app/data
      - ./contracts:/app/contracts
    environment:
      CLIENT_ID: "0"
      SERVER_ADDRESS: "fl-server:8080"
      LOCAL_EPOCHS: "5"
      DATA_PATH: "/app/data/client_0/transactions_normalized.parquet"
    depends_on:
      - fl-server

  fl-client-1:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      - fraud-net
    volumes:
      - ./data/processed:/app/data
      - ./contracts:/app/contracts
    environment:
      CLIENT_ID: "1"
      SERVER_ADDRESS: "fl-server:8080"
      LOCAL_EPOCHS: "5"
      DATA_PATH: "/app/data/client_1/transactions_normalized.parquet"
    depends_on:
      - fl-server

  fl-client-2:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      - fraud-net
    volumes:
      - ./data/processed:/app/data
      - ./contracts:/app/contracts
    environment:
      CLIENT_ID: "2"
      SERVER_ADDRESS: "fl-server:8080"
      LOCAL_EPOCHS: "5"
      DATA_PATH: "/app/data/client_2/transactions_normalized.parquet"
    depends_on:
      - fl-server

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    networks:
      - fraud-net
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow
    volumes:
      - ./mlruns:/mlflow

  api-gateway:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - fraud-net
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./contracts:/app/contracts
    depends_on:
      - fl-server

  drift-monitor:
    build:
      context: .
      dockerfile: drift/Dockerfile
    ports:
      - "9090:9090"
    networks:
      - fraud-net
    volumes:
      - ./data:/app/data
      - ./contracts:/app/contracts
    depends_on:
      - fl-server

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    networks:
      - fraud-net
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - fraud-net
    volumes:
      - ./monitoring/grafana_dashboards:/var/lib/grafana/dashboards

networks:
  fraud-net:
    driver: bridge